/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package number_client;

/**
 *
 * @author Mithu
 */
public class NumberClient extends javax.swing.JFrame {

    /**
     * Creates new form NumberClient
     */
    public NumberClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l1 = new java.awt.Label();
        t1 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        cb1 = new javax.swing.JComboBox();
        b1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        l1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        l1.setName(""); // NOI18N
        l1.setText("Numerophile");

        l4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l4.setText("Low");

        l2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2.setText("High");

        l3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l3.setText("Number");

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Prime Number", "Palindrome Number", "Fibonacci Number", "Even Number", "Odd Number", "Random Number","Power of 2","Perfect Cube","Perfect Square","CompositeNumber" }));
        cb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb1MouseClicked(evt);
            }
        });

        b1.setText("Generate");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l4)
                .addGap(140, 140, 140)
                .addComponent(l2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l3)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l4)
                    .addComponent(l2)
                    .addComponent(l3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        // TODO add your handling code here:
        int low=Integer.parseInt(t1.getText().toString());
        int high=Integer.parseInt(t2.getText().toString());
        String text=cb1.getSelectedItem().toString();
        String ans="";
        if(text.equals("Prime Number"))
        {
           ans=prime(low, high);
           ta1.setText(ans);
        }
        else if(text.equals("Palindrome Number"))
        {
            ans=palindromeRange(low, high);
            ta1.setText(ans);
        }
        else if(text.equals("CompositeNumber"))
        {
            ans=composite(low, high);
            ta1.setText(ans);
        }
        else if(text.equals("Fibonacci Number"))
        {
            ans=fibonacciRange(low, high);
            ta1.setText(ans);
        }
        else if(text.equals("Even Number"))
        {
            ans=evenRange(low, high);
            ta1.setText(ans);
        }
        else if(text.equals("Odd Number"))
        {
            ans=oddRange(low, high);
            ta1.setText(ans);
        }
        else if(text.equals("Random Number"))
        {
            int n=Integer.parseInt(t3.getText().toString());
            ans=randomNumberRange(low,high,n);
            ta1.setText(ans);
        }
        else if(text.equals("Power of 2"))
        {
            ans=powerOfTwoRange(low, high);
            ta1.setText(ans);
        }
        else if(text.equals("Perfect Cube"))
        {
            ans=perfectCubeRange(low, high);
            ta1.setText(ans);
        }
        else if(text.equals("Perfect Square"))
        {
            ans=perfectSquare(low, high);
            ta1.setText(ans);
        }
  
    }//GEN-LAST:event_b1MouseClicked

    private void cb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb1MouseClicked
        // TODO add your handling code here:
        String text=cb1.getSelectedItem().toString();
        if(text.equals("Prime Number"))
        {
            t3.setVisible(false);
            l3.setVisible(false);
        }
        else if(text.equals("Palindrome Number"))
        {
            t3.setVisible(false);
            l3.setVisible(false);
        }
        else if(text.equals("CompositeNumber"))
        {
            t3.setVisible(false);
            l3.setVisible(false);
        }
        else if(text.equals("Fibonacci Number"))
        {
            t3.setVisible(false);
            l3.setVisible(false);
        }
        else if(text.equals("Even Number"))
        {
            t3.setVisible(false);
            l3.setVisible(false);
        }
        else if(text.equals("Odd Number"))
        {
            t3.setVisible(false);
            l3.setVisible(false);
        }
        else if(text.equals("Random Number"))
        {
            t3.setVisible(true);
            l3.setVisible(true);
            
        }
        else if(text.equals("Power of 2"))
        {
            t3.setVisible(false);
            l3.setVisible(false);
        }
        else if(text.equals("Perfect Cube"))
        {
            t3.setVisible(false);
            l3.setVisible(false);
        }
        else if(text.equals("Perfect Square"))
        {
            t3.setVisible(false);
            l3.setVisible(false);
        }
    }//GEN-LAST:event_cb1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JComboBox cb1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables

    private static String randomNumberRange(int low, int high, int n) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.randomNumberRange(low, high, n);
    }

    private static String composite(int low, int high) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.composite(low, high);
    }

    private static String evenRange(int low, int high) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.evenRange(low, high);
    }

    private static String fibonacciRange(int low, int high) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.fibonacciRange(low, high);
    }

    private static String oddRange(int low, int high) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.oddRange(low, high);
    }

    private static String palindromeRange(int low, int high) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.palindromeRange(low, high);
    }

    private static String perfectCubeRange(int low, int high) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.perfectCubeRange(low, high);
    }

    private static String perfectSquare(int low, int high) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.perfectSquare(low, high);
    }

    private static String powerOfTwoRange(int low, int high) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.powerOfTwoRange(low, high);
    }

    private static String prime(int low, int high) {
        number_client.Numbers_Service service = new number_client.Numbers_Service();
        number_client.Numbers port = service.getNumbersPort();
        return port.prime(low, high);
    }
    
    
}
